
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using JSON_Deserealising_Test;
//
//    var farm = Farm.FromJson(jsonString);

using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using J = Newtonsoft.Json.JsonPropertyAttribute;
using R = Newtonsoft.Json.Required;
using N = Newtonsoft.Json.NullValueHandling;

namespace JSON_Deserealising_Test
{
    public partial class Farm
    {
        [J("id")] public long Id { get; set; }
        [J("threebot_id")] public long ThreebotId { get; set; }
        [J("iyo_organization")] public string IyoOrganization { get; set; }
        [J("name")] public string Name { get; set; }
        [J("wallet_addresses")] public List<WalletAddress> WalletAddresses { get; set; }
        [J("location")] public FarmLocation Location { get; set; }
        [J("email")] public string Email { get; set; }
        [J("resource_prices")] public List<object> ResourcePrices { get; set; }
        [J("prefix_zero")] public string PrefixZero { get; set; }
    }

    public partial class FarmLocation
    {
        [J("city")] public string City_farm { get; set; }
        [J("country")] public string Country_farm { get; set; }
        [J("continent")] public string Continent_farm { get; set; }
        [J("latitude")] public long Latitude_farm { get; set; }
        [J("longitude")] public long Longitude_farm { get; set; }
    }

    public partial class WalletAddress
    {
        [J("asset")] public string Asset { get; set; }
        [J("address")] public string Address { get; set; }
    }

    public partial class Farm
    {
        public static Farm FromJson(string json) => JsonConvert.DeserializeObject<Farm>(json, FarmConverter.Settings);
    }
    public partial class Farm
    {
        public static List<Farm> FromJsonList(string jsonList) => JsonConvert.DeserializeObject<List<Farm>>(jsonList, FarmConverter.Settings);
    }

    public static class FarmSerialize
    {
        public static string ToJson(this Farm self) => JsonConvert.SerializeObject(self, FarmConverter.Settings);
    }

    internal static class FarmConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}