FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["DockerWebAPI-Linux-Test/DockerWebAPI-Linux-Test.csproj", "DockerWebAPI-Linux-Test/"]

RUN dotnet restore "DockerWebAPI-Linux-Test/DockerWebAPI-Linux-Test.csproj"
COPY . .
WORKDIR "/src/DockerWebAPI-Linux-Test"
RUN dotnet build --no-restore "DockerWebAPI-Linux-Test.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]